/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Text;
export const CommentId = IDL.Text;
export const Timestamp = IDL.Int;
export const CommentWithContext = IDL.Record({
  'id' : CommentId,
  'isLiked' : IDL.Bool,
  'likeCount' : IDL.Nat,
  'authorAvatar' : IDL.Text,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorHandle' : IDL.Text,
  'videoId' : VideoId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateVideoArgs = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'category' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'expiresAt' : IDL.Opt(Timestamp),
  'giftCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'trendingScore' : IDL.Float64,
  'description' : IDL.Text,
  'uploaderHandle' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'shareCount' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
  'uploaderId' : UserId,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : UserId,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'coinBalance' : IDL.Nat,
  'joinedAt' : Timestamp,
  'totalLikes' : IDL.Nat,
  'totalVideos' : IDL.Nat,
  'followerCount' : IDL.Nat,
  'handle' : IDL.Text,
  'followingCount' : IDL.Nat,
  'totalCoinsEarned' : IDL.Nat,
});
export const CoinPack = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'coins' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const TransactionId = IDL.Text;
export const TransactionType = IDL.Variant({
  'gift_sent' : IDL.Null,
  'gift_received' : IDL.Null,
  'purchase' : IDL.Null,
});
export const CoinTransaction = IDL.Record({
  'id' : TransactionId,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Text,
  'userPrincipal' : UserId,
  'amount' : IDL.Nat,
});
export const GiftId = IDL.Text;
export const Gift = IDL.Record({
  'id' : GiftId,
  'coinValue' : IDL.Nat,
  'createdAt' : Timestamp,
  'giftEmoji' : IDL.Text,
  'receiverPrincipal' : UserId,
  'senderPrincipal' : UserId,
  'videoId' : VideoId,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SaveProfileArgs = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'handle' : IDL.Text,
});
export const GiftType = IDL.Variant({
  'heart' : IDL.Null,
  'rose' : IDL.Null,
  'crown' : IDL.Null,
  'diamond' : IDL.Null,
  'rocket' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [CommentWithContext], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createVideo' : IDL.Func([CreateVideoArgs], [Video], []),
  'deleteComment' : IDL.Func([VideoId, CommentId], [], []),
  'deleteVideo' : IDL.Func([VideoId], [], []),
  'editVideo' : IDL.Func(
      [VideoId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Video],
      [],
    ),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCoinPacks' : IDL.Func([], [IDL.Vec(CoinPack)], ['query']),
  'getCoinTransactions' : IDL.Func([], [IDL.Vec(CoinTransaction)], ['query']),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(CommentWithContext)], []),
  'getCreatorEarnings' : IDL.Func(
      [],
      [IDL.Record({ 'totalCoins' : IDL.Nat, 'recentGifts' : IDL.Vec(Gift) })],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrendingVideos' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'getVideos' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Nat],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'incrementShare' : IDL.Func([VideoId], [], []),
  'incrementView' : IDL.Func([VideoId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func([VideoId, CommentId], [], []),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'purchaseCoins' : IDL.Func([IDL.Text, IDL.Text], [CoinTransaction], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileArgs], [UserProfile], []),
  'sendGift' : IDL.Func([VideoId, GiftType], [Gift], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unlikeComment' : IDL.Func([VideoId, CommentId], [], []),
  'unlikeVideo' : IDL.Func([VideoId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Text;
  const CommentId = IDL.Text;
  const Timestamp = IDL.Int;
  const CommentWithContext = IDL.Record({
    'id' : CommentId,
    'isLiked' : IDL.Bool,
    'likeCount' : IDL.Nat,
    'authorAvatar' : IDL.Text,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorHandle' : IDL.Text,
    'videoId' : VideoId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateVideoArgs = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'thumbnailBlob' : ExternalBlob,
    'category' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'expiresAt' : IDL.Opt(Timestamp),
    'giftCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'trendingScore' : IDL.Float64,
    'description' : IDL.Text,
    'uploaderHandle' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'thumbnailBlob' : ExternalBlob,
    'shareCount' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
    'uploaderId' : UserId,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : UserId,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'coinBalance' : IDL.Nat,
    'joinedAt' : Timestamp,
    'totalLikes' : IDL.Nat,
    'totalVideos' : IDL.Nat,
    'followerCount' : IDL.Nat,
    'handle' : IDL.Text,
    'followingCount' : IDL.Nat,
    'totalCoinsEarned' : IDL.Nat,
  });
  const CoinPack = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'coins' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const TransactionId = IDL.Text;
  const TransactionType = IDL.Variant({
    'gift_sent' : IDL.Null,
    'gift_received' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const CoinTransaction = IDL.Record({
    'id' : TransactionId,
    'transactionType' : TransactionType,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Text,
    'userPrincipal' : UserId,
    'amount' : IDL.Nat,
  });
  const GiftId = IDL.Text;
  const Gift = IDL.Record({
    'id' : GiftId,
    'coinValue' : IDL.Nat,
    'createdAt' : Timestamp,
    'giftEmoji' : IDL.Text,
    'receiverPrincipal' : UserId,
    'senderPrincipal' : UserId,
    'videoId' : VideoId,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SaveProfileArgs = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'handle' : IDL.Text,
  });
  const GiftType = IDL.Variant({
    'heart' : IDL.Null,
    'rose' : IDL.Null,
    'crown' : IDL.Null,
    'diamond' : IDL.Null,
    'rocket' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [CommentWithContext], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createVideo' : IDL.Func([CreateVideoArgs], [Video], []),
    'deleteComment' : IDL.Func([VideoId, CommentId], [], []),
    'deleteVideo' : IDL.Func([VideoId], [], []),
    'editVideo' : IDL.Func(
        [VideoId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Video],
        [],
      ),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCoinPacks' : IDL.Func([], [IDL.Vec(CoinPack)], ['query']),
    'getCoinTransactions' : IDL.Func([], [IDL.Vec(CoinTransaction)], ['query']),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(CommentWithContext)], []),
    'getCreatorEarnings' : IDL.Func(
        [],
        [IDL.Record({ 'totalCoins' : IDL.Nat, 'recentGifts' : IDL.Vec(Gift) })],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrendingVideos' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'getVideos' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'incrementShare' : IDL.Func([VideoId], [], []),
    'incrementView' : IDL.Func([VideoId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func([VideoId, CommentId], [], []),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'purchaseCoins' : IDL.Func([IDL.Text, IDL.Text], [CoinTransaction], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileArgs], [UserProfile], []),
    'sendGift' : IDL.Func([VideoId, GiftType], [Gift], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unlikeComment' : IDL.Func([VideoId, CommentId], [], []),
    'unlikeVideo' : IDL.Func([VideoId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };