/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoinPack {
  'id' : string,
  'displayName' : string,
  'coins' : bigint,
  'priceInCents' : bigint,
}
export interface CoinTransaction {
  'id' : TransactionId,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'referenceId' : string,
  'userPrincipal' : UserId,
  'amount' : bigint,
}
export type CommentId = string;
export interface CommentWithContext {
  'id' : CommentId,
  'isLiked' : boolean,
  'likeCount' : bigint,
  'authorAvatar' : string,
  'createdAt' : Timestamp,
  'text' : string,
  'authorHandle' : string,
  'videoId' : VideoId,
}
export interface CreateVideoArgs {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export interface Gift {
  'id' : GiftId,
  'coinValue' : bigint,
  'createdAt' : Timestamp,
  'giftEmoji' : string,
  'receiverPrincipal' : UserId,
  'senderPrincipal' : UserId,
  'videoId' : VideoId,
}
export type GiftId = string;
export type GiftType = { 'heart' : null } |
  { 'rose' : null } |
  { 'crown' : null } |
  { 'diamond' : null } |
  { 'rocket' : null };
export interface SaveProfileArgs {
  'bio' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'handle' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export type TransactionId = string;
export type TransactionType = { 'gift_sent' : null } |
  { 'gift_received' : null } |
  { 'purchase' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'principal' : UserId,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'coinBalance' : bigint,
  'joinedAt' : Timestamp,
  'totalLikes' : bigint,
  'totalVideos' : bigint,
  'followerCount' : bigint,
  'handle' : string,
  'followingCount' : bigint,
  'totalCoinsEarned' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'likeCount' : bigint,
  'expiresAt' : [] | [Timestamp],
  'giftCount' : bigint,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'trendingScore' : number,
  'description' : string,
  'uploaderHandle' : string,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'shareCount' : bigint,
  'viewCount' : bigint,
  'commentCount' : bigint,
  'category' : string,
  'uploaderId' : UserId,
}
export type VideoId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[VideoId, string], CommentWithContext>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createVideo' : ActorMethod<[CreateVideoArgs], Video>,
  'deleteComment' : ActorMethod<[VideoId, CommentId], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  'editVideo' : ActorMethod<
    [VideoId, string, string, Array<string>, string],
    Video
  >,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getCoinPacks' : ActorMethod<[], Array<CoinPack>>,
  'getCoinTransactions' : ActorMethod<[], Array<CoinTransaction>>,
  'getComments' : ActorMethod<[VideoId], Array<CommentWithContext>>,
  'getCreatorEarnings' : ActorMethod<
    [],
    { 'totalCoins' : bigint, 'recentGifts' : Array<Gift> }
  >,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrendingVideos' : ActorMethod<[[] | [string], bigint], Array<Video>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'getVideos' : ActorMethod<
    [[] | [string], [] | [bigint], bigint],
    Array<Video>
  >,
  'incrementShare' : ActorMethod<[VideoId], undefined>,
  'incrementView' : ActorMethod<[VideoId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeComment' : ActorMethod<[VideoId, CommentId], undefined>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'purchaseCoins' : ActorMethod<[string, string], CoinTransaction>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileArgs], UserProfile>,
  'sendGift' : ActorMethod<[VideoId, GiftType], Gift>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unlikeComment' : ActorMethod<[VideoId, CommentId], undefined>,
  'unlikeVideo' : ActorMethod<[VideoId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];