/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    likeCount: bigint;
    expiresAt?: Timestamp;
    giftCount: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    trendingScore: number;
    description: string;
    uploaderHandle: string;
    videoBlob: ExternalBlob;
    thumbnailBlob: ExternalBlob;
    shareCount: bigint;
    viewCount: bigint;
    commentCount: bigint;
    category: string;
    uploaderId: UserId;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SaveProfileArgs {
    bio: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
    handle: string;
}
export interface Gift {
    id: GiftId;
    coinValue: bigint;
    createdAt: Timestamp;
    giftEmoji: string;
    receiverPrincipal: UserId;
    senderPrincipal: UserId;
    videoId: VideoId;
}
export interface CommentWithContext {
    id: CommentId;
    isLiked: boolean;
    likeCount: bigint;
    authorAvatar: string;
    createdAt: Timestamp;
    text: string;
    authorHandle: string;
    videoId: VideoId;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type TransactionId = string;
export interface CoinTransaction {
    id: TransactionId;
    transactionType: TransactionType;
    createdAt: Timestamp;
    referenceId: string;
    userPrincipal: UserId;
    amount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type VideoId = string;
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CreateVideoArgs {
    title: string;
    tags: Array<string>;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob: ExternalBlob;
    category: string;
}
export type GiftId = string;
export type CommentId = string;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CoinPack {
    id: string;
    displayName: string;
    coins: bigint;
    priceInCents: bigint;
}
export interface UserProfile {
    bio: string;
    principal: UserId;
    displayName: string;
    avatarBlob?: ExternalBlob;
    coinBalance: bigint;
    joinedAt: Timestamp;
    totalLikes: bigint;
    totalVideos: bigint;
    followerCount: bigint;
    handle: string;
    followingCount: bigint;
    totalCoinsEarned: bigint;
}
export enum GiftType {
    heart = "heart",
    rose = "rose",
    crown = "crown",
    diamond = "diamond",
    rocket = "rocket"
}
export enum TransactionType {
    gift_sent = "gift_sent",
    gift_received = "gift_received",
    purchase = "purchase"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addComment(videoId: VideoId, text: string): Promise<CommentWithContext>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createVideo(args: CreateVideoArgs): Promise<Video>;
    deleteComment(videoId: VideoId, commentId: CommentId): Promise<void>;
    deleteVideo(videoId: VideoId): Promise<void>;
    editVideo(videoId: VideoId, title: string, description: string, tags: Array<string>, category: string): Promise<Video>;
    followUser(target: UserId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoinBalance(): Promise<bigint>;
    getCoinPacks(): Promise<Array<CoinPack>>;
    getCoinTransactions(): Promise<Array<CoinTransaction>>;
    getComments(videoId: VideoId): Promise<Array<CommentWithContext>>;
    getCreatorEarnings(): Promise<{
        totalCoins: bigint;
        recentGifts: Array<Gift>;
    }>;
    getMyProfile(): Promise<UserProfile>;
    getProfile(userId: UserId): Promise<UserProfile | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTrendingVideos(category: string | null, limit: bigint): Promise<Array<Video>>;
    getVideo(videoId: VideoId): Promise<Video | null>;
    getVideos(category: string | null, cursor: bigint | null, limit: bigint): Promise<Array<Video>>;
    incrementShare(videoId: VideoId): Promise<void>;
    incrementView(videoId: VideoId): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeComment(videoId: VideoId, commentId: CommentId): Promise<void>;
    likeVideo(videoId: VideoId): Promise<void>;
    purchaseCoins(packId: string, sessionId: string): Promise<CoinTransaction>;
    saveCallerUserProfile(args: SaveProfileArgs): Promise<UserProfile>;
    sendGift(videoId: VideoId, giftType: GiftType): Promise<Gift>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unfollowUser(target: UserId): Promise<void>;
    unlikeComment(videoId: VideoId, commentId: CommentId): Promise<void>;
    unlikeVideo(videoId: VideoId): Promise<void>;
}
import type { CoinTransaction as _CoinTransaction, CreateVideoArgs as _CreateVideoArgs, ExternalBlob as _ExternalBlob, GiftType as _GiftType, SaveProfileArgs as _SaveProfileArgs, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, TransactionId as _TransactionId, TransactionType as _TransactionType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addComment(arg0: VideoId, arg1: string): Promise<CommentWithContext> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createVideo(arg0: CreateVideoArgs): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(await to_candid_CreateVideoArgs_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Video_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(await to_candid_CreateVideoArgs_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Video_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: VideoId, arg1: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async editVideo(arg0: VideoId, arg1: string, arg2: string, arg3: Array<string>, arg4: string): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.editVideo(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Video_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editVideo(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Video_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance();
            return result;
        }
    }
    async getCoinPacks(): Promise<Array<CoinPack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinPacks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinPacks();
            return result;
        }
    }
    async getCoinTransactions(): Promise<Array<CoinTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinTransactions();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinTransactions();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: VideoId): Promise<Array<CommentWithContext>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getCreatorEarnings(): Promise<{
        totalCoins: bigint;
        recentGifts: Array<Gift>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorEarnings();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingVideos(arg0: string | null, arg1: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingVideos(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingVideos(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideos(arg0: string | null, arg1: bigint | null, arg2: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideos(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideos(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementShare(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementShare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementShare(arg0);
            return result;
        }
    }
    async incrementView(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementView(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeComment(arg0: VideoId, arg1: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0, arg1);
            return result;
        }
    }
    async likeVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeVideo(arg0);
            return result;
        }
    }
    async purchaseCoins(arg0: string, arg1: string): Promise<CoinTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseCoins(arg0, arg1);
                return from_candid_CoinTransaction_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseCoins(arg0, arg1);
            return from_candid_CoinTransaction_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileArgs): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileArgs_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileArgs_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendGift(arg0: VideoId, arg1: GiftType): Promise<Gift> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGift(arg0, to_candid_GiftType_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGift(arg0, to_candid_GiftType_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikeComment(arg0: VideoId, arg1: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeComment(arg0, arg1);
            return result;
        }
    }
    async unlikeVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeVideo(arg0);
            return result;
        }
    }
}
function from_candid_CoinTransaction_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoinTransaction): CoinTransaction {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StripeSessionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    likeCount: bigint;
    expiresAt: [] | [_Timestamp];
    giftCount: bigint;
    createdAt: _Timestamp;
    tags: Array<string>;
    trendingScore: number;
    description: string;
    uploaderHandle: string;
    videoBlob: _ExternalBlob;
    thumbnailBlob: _ExternalBlob;
    shareCount: bigint;
    viewCount: bigint;
    commentCount: bigint;
    category: string;
    uploaderId: _UserId;
}): Promise<{
    id: VideoId;
    title: string;
    likeCount: bigint;
    expiresAt?: Timestamp;
    giftCount: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    trendingScore: number;
    description: string;
    uploaderHandle: string;
    videoBlob: ExternalBlob;
    thumbnailBlob: ExternalBlob;
    shareCount: bigint;
    viewCount: bigint;
    commentCount: bigint;
    category: string;
    uploaderId: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        expiresAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.expiresAt)),
        giftCount: value.giftCount,
        createdAt: value.createdAt,
        tags: value.tags,
        trendingScore: value.trendingScore,
        description: value.description,
        uploaderHandle: value.uploaderHandle,
        videoBlob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.videoBlob),
        thumbnailBlob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.thumbnailBlob),
        shareCount: value.shareCount,
        viewCount: value.viewCount,
        commentCount: value.commentCount,
        category: value.category,
        uploaderId: value.uploaderId
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: _UserId;
    displayName: string;
    avatarBlob: [] | [_ExternalBlob];
    coinBalance: bigint;
    joinedAt: _Timestamp;
    totalLikes: bigint;
    totalVideos: bigint;
    followerCount: bigint;
    handle: string;
    followingCount: bigint;
    totalCoinsEarned: bigint;
}): Promise<{
    bio: string;
    principal: UserId;
    displayName: string;
    avatarBlob?: ExternalBlob;
    coinBalance: bigint;
    joinedAt: Timestamp;
    totalLikes: bigint;
    totalVideos: bigint;
    followerCount: bigint;
    handle: string;
    followingCount: bigint;
    totalCoinsEarned: bigint;
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        displayName: value.displayName,
        avatarBlob: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.avatarBlob)),
        coinBalance: value.coinBalance,
        joinedAt: value.joinedAt,
        totalLikes: value.totalLikes,
        totalVideos: value.totalVideos,
        followerCount: value.followerCount,
        handle: value.handle,
        followingCount: value.followingCount,
        totalCoinsEarned: value.totalCoinsEarned
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    transactionType: _TransactionType;
    createdAt: _Timestamp;
    referenceId: string;
    userPrincipal: _UserId;
    amount: bigint;
}): {
    id: TransactionId;
    transactionType: TransactionType;
    createdAt: Timestamp;
    referenceId: string;
    userPrincipal: UserId;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n26(_uploadFile, _downloadFile, value.transactionType),
        createdAt: value.createdAt,
        referenceId: value.referenceId,
        userPrincipal: value.userPrincipal,
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gift_sent: null;
} | {
    gift_received: null;
} | {
    purchase: null;
}): TransactionType {
    return "gift_sent" in value ? TransactionType.gift_sent : "gift_received" in value ? TransactionType.gift_received : "purchase" in value ? TransactionType.purchase : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n30(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoinTransaction>): Array<CoinTransaction> {
    return value.map((x)=>from_candid_CoinTransaction_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n13(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateVideoArgs_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVideoArgs): Promise<_CreateVideoArgs> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GiftType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftType): _GiftType {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_SaveProfileArgs_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileArgs): Promise<_SaveProfileArgs> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    tags: Array<string>;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob: ExternalBlob;
    category: string;
}): Promise<{
    title: string;
    tags: Array<string>;
    description: string;
    videoBlob: _ExternalBlob;
    thumbnailBlob: _ExternalBlob;
    category: string;
}> {
    return {
        title: value.title,
        tags: value.tags,
        description: value.description,
        videoBlob: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.videoBlob),
        thumbnailBlob: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.thumbnailBlob),
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
    handle: string;
}): Promise<{
    bio: string;
    displayName: string;
    avatarBlob: [] | [_ExternalBlob];
    handle: string;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        avatarBlob: value.avatarBlob ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.avatarBlob)) : candid_none(),
        handle: value.handle
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftType): {
    heart: null;
} | {
    rose: null;
} | {
    crown: null;
} | {
    diamond: null;
} | {
    rocket: null;
} {
    return value == GiftType.heart ? {
        heart: null
    } : value == GiftType.rose ? {
        rose: null
    } : value == GiftType.crown ? {
        crown: null
    } : value == GiftType.diamond ? {
        diamond: null
    } : value == GiftType.rocket ? {
        rocket: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
